### ISSUE TITLE
using StatsBase; workspace(); using StatsBase    gives warnings!

### ISSUE THREAD

**Issue by stefanks** [JuliaStats/StatsBase.jl#108]
Reproducible. 

Warning: Method definition stdm(AbstractArray{T<:Real,N},AbstractArray{T<:Real,N},Int64) in module StatsBase at /Users/stepa/.julia/v0.3/StatsBase/src/moments.jl:63 overwritten in module StatsBase at /Users/stepa/.julia/v0.3/StatsBase/src/moments.jl:63.
Warning: Method definition quantile(AbstractArray{T<:Real,N},) in module StatsBase at /Users/stepa/.julia/v0.3/StatsBase/src/scalarstats.jl:158 overwritten in module StatsBase at /Users/stepa/.julia/v0.3/StatsBase/src/scalarstats.jl:158.

Julia Version 0.3.5

**Comment by johnmyleswhite** [comment]
Is this unique to StatsBase? It seems like the problem is likely to be that those names are in Base.

**Comment by simonster** [comment]
This is essentially the same issue as JuliaLang/julia#7860. The problem is not just that the names are in Base, but that we define new methods that accept only built-in types, which is somewhat questionable. Arguably that definition of `stdm` should be `wstdm` and that definition of `quantile` either shouldn't exist or should be called `quartile`.

**Comment by Nosferican** [comment]
Should this be closed?
