### ISSUE TITLE
sample might support DataFrames

### ISSUE THREAD

**Issue by scls19fr** [JuliaStats/StatsBase.jl#170]
Hello,

it will be nice if `sample` could support `DataFrame` (when DataFrames.jl is installed)

Here is my code

```julia
function sample(df::DataFrame)
    sample(df, 1)
end

function sample(df::DataFrame, N::Integer)
    df_sample = DataFrame()
    for col in names(df)
       df_sample[col] = sample(df[col], N)
    end
    df_sample
end
```

and a possible usage

```julia
julia> using RDatasets
julia> iris=dataset("datasets", "iris")
julia> sample(iris, 5)
5×5 DataFrames.DataFrame
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ Species      │
├─────┼─────────────┼────────────┼─────────────┼────────────┼──────────────┤
│ 1   │ 5.8         │ 3.0        │ 4.4         │ 0.2        │ "versicolor" │
│ 2   │ 4.9         │ 2.4        │ 4.0         │ 1.9        │ "versicolor" │
│ 3   │ 6.5         │ 3.4        │ 4.9         │ 1.8        │ "virginica"  │
│ 4   │ 6.4         │ 2.8        │ 1.7         │ 1.3        │ "setosa"     │
│ 5   │ 6.3         │ 3.5        │ 1.3         │ 1.0        │ "setosa"     │
```

It should be possible to add this without adding `DataFrames.jl` into `StatsBase.jl` `REQUIRE`

Kind regards

**Comment by nalimilan** [comment]
> It should be possible to add this without adding DataFrames.jl into StatsBase.jl REQUIRE

Is this a statement or a question? AFAIK, that's not possible now, though it might become so in Julia 0.6. OTOH, since DataFrames.jl depends on StatsBase, we can perfectly ship this method there.

As regards the implementation, I'm a bit confused about the definition you want to give to that method. The most logical definition would be `df[sample(1:size(df, 1), N), :]`, i.e. a sampling of rows. Your code mixes the values from different row instead. Is that intended?

**Comment by scls19fr** [comment]
yes... you are right ! I didn't noticed that my code was mixing the values from different row.

**Comment by diegozea** [comment]
I also think that would be great to define the `sample` method for `DataFrame`s in the DataFrames package.

**Comment by nalimilan** [comment]
Let's close this. Please make a PR against DataFrames instead.
