### ISSUE TITLE
CoefTable in function

### ISSUE THREAD

**Issue by mingsnu** [JuliaStats/StatsBase.jl#211]
I found that `CoefTable` can only be run once inside a function. Take the following code as an example, each CoefTable works fine when running them in REPL but only the last one is executed when running in the test function. Any body knows what's happening there?
Thank you!

```
function test()
    CoefTable([1, 2, 3], ["a", "b", "c"], [""])
    CoefTable([10, 20, 30], ["a", "b", "c"], [""])
end
test()
```

**Comment by ararslan** [comment]
You're creating two `CoefTable` objects. In Julia, the last thing evaluated in a function is returned. So what you have is equivalent to
```julia
function test()
    CoefTable([1, 2, 3], ["a", "b", "c"], [""])
    return CoefTable([10, 20, 30], ["a", "b", "c"], [""])
end
```
The first `CoefTable` is thrown out, since it's constructed but not used. The difference when evaluating them at the REPL is the "P" in "REPL": `print`. At the REPL you're implicitly `print`ing the objects.

So to get the behavior I think you're looking for, you can wrap each `CoefTable` constructor in `println`.

**Comment by mingsnu** [comment]
Hi Alex,
Thank you so much for your explanation, it helps a lot!
I'm an R user and I'm just getting started to explore julia:)

**Comment by ararslan** [comment]
I'm glad I could help, and that you're checking out Julia. All the best!

**Comment by mingsnu** [comment]
Thank you!
