### ISSUE TITLE
Correlation to Covariance

### ISSUE THREAD

**Issue by mes9** [JuliaStats/StatsBase.jl#246]
It would be useful to have a function in StatsBase that allows us to define a distribution with the correlation matrix or to go from the correlation matrix to the covariance matrix.

Matlab has a nice function for that, corr2cov:
https://www.mathworks.com/help/finance/corr2cov.html

If something like this already exists in Julia, please let me know!

**Comment by ararslan** [comment]
The Base library has `cov2cor!`, though it's neither exported nor documented: https://github.com/JuliaLang/julia/blob/master/base/statistics.jl#L402

**Comment by rofinn** [comment]
AFAIK, you can manipulate `sqrtcor` (where `cor = sqrtcor'sqrtcor`), so that I can compute the pearson correlation or covariance (with a qr decomposition) as needed. I've worked on code which does this, but I'm not sure how common this approach is or whether it warrants being included in StatsBase though.
