### ISSUE TITLE
Corrected var, std, cov and cor

### ISSUE THREAD

**Issue by rofinn** [JuliaStats/StatsBase.jl#249]
Hi,

I'd like to restart the discussion on supporting corrected versions of the `var`, `std`, `cov` and `cor` functions (preferably by default). I see there was an [issue](https://github.com/JuliaStats/StatsBase.jl/issues/53) a long time ago that made a lot of good points, but folks decided to stick with the uncorrected versions. I like the idea of using different types for representing different weighting methods (e.g., frequency, reliability, analytic), but perhaps we could just add a `bias` field to the `WeightVec` and infer between `frequency` and `reliability` at construction time. For example, if the weights are `Int`s and the sum is of type `Int` then use the frequency bias, otherwise use the reliability bias?

I mostly bring this up because it seems a bit unintuitive for new users that `std(X, 1)` and `std(X, ones(n), 1)` don't produce the same output.

**Comment by nalimilan** [comment]
Using the storage type to decide what's the meaning of weights doesn't sound a good idea to me. For example, many surveys datasets come with integer weights which are sampling weights and not case weights at all.

How about adding `SamplingWeights`, `CaseWeights` and `AnalyticWeights` types as discussed in https://github.com/JuliaStats/StatsBase.jl/issues/53? We'll need these at some point anyway for modelling functions.

Regarding the default behavior of  `std(X, ones(n), 1)`, I'm not sure what's the best approach. Assuming these are case weights sounds like a strong assumption. We could require people to specify the kind of weights they are passing (e.g. `std(X, CaseWeights(ones(n)), 1)`), but this could be too annoying.

**Comment by Rory-Finnegan** [comment]
> Using the storage type to decide what's the meaning of weights doesn't sound a good idea to me. For example, many surveys datasets come with integer weights which are sampling weights and not case weights at all.

That's a good point, making the assumption that integer weights are frequency weight might just create more confusion.

> How about adding SamplingWeights, CaseWeights and AnalyticWeights types as discussed in #53? We'll need these at some point anyway for modelling functions.

My only hesitation with this is that it would require more significant refactoring of the `WeightVec` code and would probably result in at least a minor version release. For example, we'd probably want to rename `WeightVec` to `AbstractWeights` and define a very clear API for all subtypes. If we take this approach it might make sense to move most of the weight vector implementations into a separate package and have the rest of StatsBase operate on the abstract type. A benefit of all of this is that we could implement just a few weight types to start and it should be pretty easy for folks to add new types as they need. I only suggested `frequency` and `reliability` weights first because they seemed like the most common (based on some quick google searching) and I'm not particularly familiar with the other types (or different names for the same types?).

> Regarding the default behavior of std(X, ones(n), 1), I'm not sure what's the best approach. Assuming these are case weights sounds like a strong assumption. We could require people to specify the kind of weights they are passing (e.g. std(X, CaseWeights(ones(n)), 1)), but this could be too annoying.

I guess you currently need to do `std(X, weights(ones(n)), 1)`, so maybe just having something like `std(X, frequency(ones(n)), 1)` or `std(X, reliability(ones(n)), 1)` isn't that big of a problem.

Overall, if folks have a preference for a more formal `AbstractWeight` type hierarchy then I can work on a prototype.

**Comment by nalimilan** [comment]
> My only hesitation with this is that it would require more significant refactoring of the WeightVec code and would probably result in at least a minor version release.

Doesn't sound an issue, we make releases all the time and the deprecation path is easy.

> For example, we'd probably want to rename WeightVec to AbstractWeights and define a very clear API for all subtypes. If we take this approach it might make sense to move most of the weight vector implementations into a separate package and have the rest of StatsBase operate on the abstract type.

I don't think a separate package is worth it. These would be very simple types, and most of the code already exists in StatsBase.

> A benefit of all of this is that we could implement just a few weight types to start and it should be pretty easy for folks to add new types as they need. I only suggested frequency and reliability weights first because they seemed like the most common (based on some quick google searching) and I'm not particularly familiar with the other types (or different names for the same types?).

Sampling/probability weights are also quite common. The only other type from [my old list](https://github.com/JuliaStats/StatsBase.jl/issues/53#issuecomment-39653253) is importance weights, which have no defined meaning: we could probably start without these and see whether there's a real need for them.

> I guess you currently need to do std(X, weights(ones(n)), 1), so maybe just having something like std(X, frequency(ones(n)), 1) or std(X, reliability(ones(n)), 1) isn't that big of a problem.
> 
> Overall, if folks have a preference for a more formal AbstractWeight type hierarchy then I can work on a prototype.

That would be great. I've been willing to do this for a long time but never got down to it.

**Comment by oschulz** [comment]
> That's a good point, making the assumption that integer weights are frequency weight might just create more confusion.

I agree.
