### ISSUE TITLE
sampling is very slow because it uses a linear search

### ISSUE THREAD

**Issue by skariel** [JuliaStats/StatsBase.jl#421]
using a `searchsortedfirst` one can achieve orders of magnitude improvement, depending on the size of the weights vector. The code then is also simpler and shorter (since it uses a function instead of implementing the linear sort) See benchmark below:

```julia
print("sample a lot")
a = abs.(randn(10000000))
w = Weights(a)
@btime sample($w) # --> 367.972 μs

print("sample a few")
a = abs.(randn(100))
w = Weights(a)
@btime sample($w) # --> 202.561 ns

function my_sample(ca)
    r = rand()*ca[end]
    searchsortedfirst(ca,r)
end

print("my_sample a lot")
a = abs.(randn(10000000))
ca = cumsum(a)
@btime my_sample($ca) # --> 873.300 ns (~100x faster than sample)

print("my_sample a few")
a = abs.(randn(100))
ca = cumsum(a)
@btime my_sample($ca); # --> 110.296 ns (~3x faster than sample)
```

**Comment by simonbyrne** [comment]
But `cumsum` is still a linear operation, so for a single sample there is no net benefit.

If you want to do pre-processing, then you would be better off constructing an [alias table](https://en.wikipedia.org/wiki/Alias_method), in which case you can then sample in O(1) instead of O(log(n)) (the cost of using `searchsortedfirst`).

See https://stackoverflow.com/a/52084353/392585

**Comment by skariel** [comment]
ahhh yep, of course, you're right :)
