### ISSUE TITLE
`countmap` with comparisons other than `==`

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/StatsBase.jl#717]
Sometimes I'd like to build a countmap that compares using an operator other than `==` -- for instance, I might want to build a countmap using `≈` to decide whether two objects are (close enough) to equal, or maybe `isseteq`. It might be a good idea to add a third argument, defaulting to `==`, that lets you do this.

**Comment by mschauer** [comment]
`countmap` is dictionary or Radix sort based, so there are no mutual comparisons with `==` either as far as I can see.

**Comment by nalimilan** [comment]
Grouping using `≈` is a very difficult and ill-defined problem as it's not a transitive operation. Grouping with `==` is also tricky due to things like `NaN == NaN` returning `false`, not to mention `missing`.

Anyway we would need a precise use case to evaluate whether something can be done about it.

**Comment by mschauer** [comment]
Maybe nice to point out, that grouping in approximately equal groups is a form of clustering and you can look at https://github.com/JuliaStats/Clustering.jl and perhaps  try https://en.wikipedia.org/wiki/K-means_clustering
