### ISSUE TITLE
std,var return NaN when there is only one element in array.

### ISSUE THREAD

**Issue by liupgd** [JuliaStats/StatsBase.jl#889]
```julia
using StatsBase
a = [1.0]
std(a) # --> returns NaN
var(a) # --> returns NaN
```
Is this normal? I thought they should return 0.

**Comment by ararslan** [comment]
This is because `var` and `std` apply [Bessel's correction](https://en.wikipedia.org/wiki/Bessel%27s_correction) by default. When your sample size is $n = 1$, the sum of squared deviations from the mean is multiplied by $\frac{1}{n} = 1$ without the correction, which will give you 0. But with the correction, $\frac{1}{n - 1} = \frac{1}{0} = \text{NaN}$ since Julia's Base float types and arithmetic follow the IEEE 754 standard.
